Revert "bootloader: align with AOSP code"
This reverts commit 4e0e3fcfdb4f769121678d9bcc28ed3f77b5a36c.

Fixes error:-
bootable/recovery/roots.h:30:1: error: 'Volume' does not name a type  Volume* volume_for_path(const char* path);

Signed-off-by: NoelMacwan <yulespencer@gmail.com>